apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-fastapi-app
  namespace: redis-enterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-fastapi
  template:
    metadata:
      labels:
        app: redis-fastapi
    spec:
      containers:
      - name: redis-fastapi
        image: redis-fastapi-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
