apiVersion: v1
kind: Service
metadata:
  name: redis-fastapi-service
  namespace: redis-enterprise
spec:
  selector:
    app: redis-fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort  # For external access (or ClusterIP for internal only)
